# Generated by Django 4.1.2 on 2022-11-07 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklistquestionresponse",
            name="answer",
            field=models.CharField(
                choices=[
                    ("NO", "No"),
                    ("YES", "Yes"),
                    ("NOT", "This isn't relevant to me"),
                ],
                default="NOT",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="note_type",
            field=models.CharField(
                choices=[
                    ("PA", "Pathway Plan PA"),
                    ("MANAGER", "Pathway Plan Manager"),
                ],
                default="PA",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="personaladvisor",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personal_advisors",
                to="core.personaladvisor",
            ),
        ),
    ]
