# Generated by Django 4.1.3 on 2022-11-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_checklistquestionresponse_answer_and_more"),
        ("core", "0002_remove_personaladvisor_is_manager_and_more"),
    ]

    operations = []
