# Generated by Django 4.1.3 on 2022-11-08 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_merge_20221108_1448"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaladvisor",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personal_advisors",
                to="core.manager",
            ),
        ),
    ]
