# Generated by Django 4.1.2 on 2022-11-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_merge_20221108_1448"),
    ]

    operations = [
        migrations.RenameField(
            model_name="action",
            old_name="created_at",
            new_name="at",
        ),
        migrations.RenameField(
            model_name="action",
            old_name="completed_by",
            new_name="by",
        ),
        migrations.RenameField(
            model_name="goal",
            old_name="created_at",
            new_name="at",
        ),
        migrations.RenameField(
            model_name="goal",
            old_name="completed_by",
            new_name="by",
        ),
        migrations.RemoveField(
            model_name="action",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="action",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="action",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="action",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="updated_by",
        ),
    ]
