# Generated by Django 4.1.2 on 2023-01-10 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_action_completed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaladvisor",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personal_advisors",
                to="core.manager",
            ),
        ),
    ]
