# Generated by Django 4.1.2 on 2023-02-17 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_personaladvisor_manager"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="checklistquestionresponse",
            unique_together={("checklist_response", "question")},
        ),
        migrations.AlterUniqueTogether(
            name="checklistresponse",
            unique_together={("checklist", "young_person")},
        ),
    ]
