# Generated by Django 4.1.2 on 2023-03-22 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0005_alter_personaladvisor_manager"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckInQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=500)),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkin_questions",
                        to="core.checklist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckInResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_checkin_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "young_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkin_responses",
                        to="core.youngperson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckInQuestionResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        choices=[("GOOD", "Good"), ("OK", "OK"), ("BAD", "Bad")],
                        default="OK",
                        max_length=4,
                    ),
                ),
                ("help_flag", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True, max_length=500, null=True)),
                (
                    "checkin_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkin_question_response_instance",
                        to="core.checkinresponse",
                    ),
                ),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkin_checklist",
                        to="core.checklist",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkin_question_responses",
                        to="core.checkinquestion",
                    ),
                ),
            ],
        ),
    ]
