# Generated by Django 4.1.2 on 2023-03-30 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_checkinquestion_checkinresponse_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkinquestionresponse",
            name="checklist",
        ),
    ]
